name: Dachs MQTT Bridge
version: "1.0.0"
slug: dachs_mqtt
description: MQTT bridge for Dachs
arch:
  - amd64
  - aarch64
startup: application
boot: auto
image: ghcr.io/schpuntik/ha-dachs-mqtt/dachs_mqtt-{arch}

build_from:
  amd64: ghcr.io/home-assistant/amd64-base-python:3.11
  aarch64: ghcr.io/home-assistant/aarch64-base-python:3.11
