name: Dachs MQTT Bridge
version: "latest"
slug: dachs_mqtt
description: MQTT bridge for Dachs
arch:
  - amd64
  - aarch64
startup: application
boot: auto

image: ghcr.io/schpuntik/ha-dachs-mqtt/dachs_mqtt-{arch}
