name: Dachs MQTT Bridge
version: "1.0.2"
slug: dachs_mqtt
description: Reads Dachs values and publishes them to MQTT with HA Discovery
startup: services
boot: auto
host_network: true

arch:
  - amd64
  - aarch64
  - armv7
  - armhf
  - i386

options:
  dachs_host: 192.168.178.52
  dachs_user: glt
  dachs_password: PASSWORT
  mqtt_host: 192.168.178.10
  mqtt_port: 1883
  mqtt_user: ""
  mqtt_password: ""
  topic_prefix: dachs
  interval: 15

schema:
  dachs_host: str
  dachs_user: str
  dachs_password: str
  mqtt_host: str
  mqtt_port: int
  mqtt_user: str?
  mqtt_password: str?
  topic_prefix: str
  interval: int

image: ghcr.io/schpuntik/ha-dachs-mqtt/dachs_mqtt-{arch}
