name: Dachs MQTT Bridge
version: "1.0.1"
slug: dachs_mqtt
description: MQTT bridge for Dachs
arch:
  - amd64
  - aarch64
startup: application
boot: auto
image: ghcr.io/schpuntik/ha-dachs-mqtt/dachs_mqtt-{arch}

build_from:
  amd64: ghcr.io/home-assistant/amd64-addon-base-python3:3.12
  aarch64: ghcr.io/home-assistant/aarch64-addon-base-python3:3.12
